[cryptoMaterial]

certPath = "/app/fisco-sdk"                 # The certification path (容器内挂载路径)  

# The following configurations take the certPath by default if commented
# caCert = "conf/ca.crt"                    # CA cert file path
                                            # If connect to the GM node, default CA cert path is ${certPath}/gm/gmca.crt

# sslCert = "conf/sdk.crt"                  # SSL cert file path
                                            # If connect to the GM node, the default SDK cert path is ${certPath}/gm/gmsdk.crt

# sslKey = "conf/sdk.key"                   # SSL key file path
                                            # If connect to the GM node, the default SDK privateKey path is ${certPath}/gm/gmsdk.key

# enSslCert = "conf/gm/gmensdk.crt"         # GM encryption cert file path
                                            # default load the GM SSL encryption cert from ${certPath}/gm/gmensdk.crt

# enSslKey = "conf/gm/gmensdk.key"          # GM ssl cert file path
                                            # default load the GM SSL encryption privateKey from ${certPath}/gm/gmensdk.key

[network]
# FISCO 本地节点地址（容器使用 host 网络，可直接访问 127.0.0.1）
peers=["127.0.0.1:20200", "127.0.0.1:20201"]    # The peer list to connect (宿主机IP)

# Configure a private topic as a topic message sender.
# [[amop]]
# topicName = "PrivateTopic1"
# publicKeys = [ "conf/amop/consumer_public_key_1.pem" ]    # Public keys of the nodes that you want to send AMOP message of this topic to.

# Configure a private topic as a topic subscriber.
# [[amop]]
# topicName = "PrivateTopic2"
# privateKey = "conf/amop/consumer_private_key.p12"         # Your private key that used to subscriber verification.
# password = "123456"

[account]
keyStoreDir = "/app/account"    # The directory to load/store the account file (容器内挂载路径)
accountFilePath = "/app/account/gm/0x1cadfbc03bd63e8d37e7f7fcd7d88300a4fa755b.pem"  # The account file path (国密账户)
accountFileFormat = "pem"       # The storage format of account file (Default is "pem", "p12" as an option)

accountAddress = "0x1cadfbc03bd63e8d37e7f7fcd7d88300a4fa755b"           # The transactions sending account address (国密账户)

# password = ""                 # The password used to load the account file

[threadPool]
# channelProcessorThreadSize = "16"         # The size of the thread pool to process channel callback
                                            # Default is the number of cpu cores

# receiptProcessorThreadSize = "16"         # The size of the thread pool to process transaction receipt notification
                                            # Default is the number of cpu cores

maxBlockingQueueSize = "102400"             # The max blocking queue size of the thread pool
